apiVersion: v2
appVersion: "2022"
description: SQL Server 2022 Linux Helm Chart
home: https://hub.docker.com/r/microsoft/mssql-server-linux/
icon: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1I4Dx
maintainers:
- email: info@simcube.co.uk
  name: simcube
name: mssqlserver-2022
sources:
- https://hub.docker.com/r/microsoft/mssql-server-linux/
version: "1.1.0"
